package catalog

type Package struct {
	Name         string
	Description  string
	PackageID    string
	CategoryType string
	Selected     bool
	Prerelease   bool
}

type Category struct {
	Name         string
	Description  string
	CategoryType string
	Categories   []Category
	Apps         []Package
}

func Default() []Category {
	return []Category{
		{
			Name:         "Browsers",
			CategoryType: "category",
			Description:  "Web browsers for everyday browsing, privacy-focused workflows, and alternate browser engines.",
			Apps: []Package{
				{Name: "Google Chrome", PackageID: "googlechrome", CategoryType: "browser", Description: "Google's web browser."},
				{Name: "Opera", PackageID: "opera", CategoryType: "browser", Description: "Opera web browser."},
				{Name: "Opera GX", PackageID: "opera-gx", CategoryType: "browser", Description: "Opera browser tuned for gaming."},
				{Name: "Mozilla Firefox", PackageID: "firefox", CategoryType: "browser", Description: "Mozilla Firefox web browser."},
				{Name: "Waterfox", PackageID: "waterfox", CategoryType: "browser", Description: "Firefox-derived browser focused on customization."},
				{Name: "Microsoft Edge", PackageID: "microsoft-edge", CategoryType: "browser", Description: "Microsoft Edge browser."},
				{Name: "Brave Browser", PackageID: "brave", CategoryType: "browser", Description: "Privacy-focused Chromium browser."},
				{Name: "Vivaldi", PackageID: "vivaldi", CategoryType: "browser", Description: "Highly customizable browser."},
				{Name: "Yandex Browser", PackageID: "yandex-browser", CategoryType: "browser", Description: "Yandex web browser."},
				{Name: "Tor Browser", PackageID: "tor-browser", CategoryType: "browser", Description: "Browser for Tor network access."},
				{Name: "LibreWolf", PackageID: "librewolf", CategoryType: "browser", Description: "Privacy-focused Firefox fork."},
				{Name: "Zen Browser", PackageID: "zen-browser", CategoryType: "browser", Description: "Modern Firefox-based browser.", Prerelease: true},
			},
		},
		{
			Name:         "Communication",
			CategoryType: "category",
			Description:  "Messaging, voice chat, video meetings, and team communication apps.",
			Apps: []Package{
				{Name: "Telegram Desktop", PackageID: "telegram", CategoryType: "communication", Description: "Telegram desktop messenger."},
				{Name: "Signal", PackageID: "signal", CategoryType: "communication", Description: "Private messaging desktop app."},
				{Name: "Element", PackageID: "element-desktop", CategoryType: "communication", Description: "Matrix-based secure chat client."},
				{Name: "Zoom", PackageID: "zoom", CategoryType: "communication", Description: "Video meetings and conferencing app."},
				{Name: "Microsoft Teams", PackageID: "microsoft-teams", CategoryType: "communication", Description: "Microsoft team chat and meetings app."},
				{Name: "Dorion", PackageID: "dorion", CategoryType: "communication", Description: "Lightweight alternative Discord client."},
			},
		},
		{
			Name:         "Development",
			CategoryType: "category",
			Description:  "Programming tools, runtimes, git tools and editors.",
			Categories: []Category{
				{
					Name:         "Editors",
					CategoryType: "subcategory",
					Description:  "Code editors and development workspaces.",
					Apps: []Package{
						{Name: "Visual Studio Code", PackageID: "vscode", CategoryType: "editor", Description: "Code editor with extensions and integrated tools."},
						{Name: "Zed", PackageID: "zed-editor", CategoryType: "editor", Description: "Fast collaborative code editor."},
						{Name: "Sublime Text", PackageID: "sublimetext4", CategoryType: "editor", Description: "Fast text and code editor."},
						{Name: "Neovim", PackageID: "neovim", CategoryType: "editor", Description: "Modern Vim-based text editor."},
						{Name: "Helix", PackageID: "helix", CategoryType: "editor", Description: "Modal code editor with built-in language support."},
						{Name: "JetBrains Toolbox", PackageID: "jetbrainstoolbox", CategoryType: "editor", Description: "JetBrains IDE manager."},
						{Name: "IntelliJ IDEA Community", PackageID: "intellijidea-community", CategoryType: "editor", Description: "JetBrains Java and JVM IDE."},
						{Name: "PyCharm Community", PackageID: "pycharm-community", CategoryType: "editor", Description: "JetBrains Python IDE."},
						{Name: "Android Studio", PackageID: "androidstudio", CategoryType: "editor", Description: "Android app development IDE."},
					},
				},
				{
					Name:         "Version Control",
					CategoryType: "subcategory",
					Description:  "Tools for tracking source code changes.",
					Apps: []Package{
						{Name: "Git", PackageID: "git", CategoryType: "version-control", Description: "Distributed version control system."},
					},
				},
				{
					Name:         "Runtimes",
					CategoryType: "subcategory",
					Description:  "Language runtimes and SDKs for development.",
					Categories: []Category{
						{
							Name:         ".NET",
							CategoryType: "runtime",
							Description:  ".NET runtimes and SDKs for building and running applications.",
							Apps: []Package{
								{Name: ".NET Runtime 10", PackageID: "dotnet-10.0-runtime", CategoryType: "runtime", Description: ".NET 10 runtime."},
								{Name: ".NET Runtime 9", PackageID: "dotnet-9.0-runtime", CategoryType: "runtime", Description: ".NET 9 runtime."},
								{Name: ".NET Runtime 8", PackageID: "dotnet-8.0-runtime", CategoryType: "runtime", Description: ".NET 8 runtime."},
								{Name: ".NET Runtime 7", PackageID: "dotnet-7.0-runtime", CategoryType: "runtime", Description: ".NET 7 runtime."},
								{Name: ".NET Runtime 6", PackageID: "dotnet-6.0-runtime", CategoryType: "runtime", Description: ".NET 6 runtime."},
								{Name: ".NET Runtime 5", PackageID: "dotnet-5.0-runtime", CategoryType: "runtime", Description: ".NET 5 runtime."},
								{Name: ".NET SDK 10", PackageID: "dotnet-10.0-sdk", CategoryType: "sdk", Description: ".NET 10 SDK."},
								{Name: ".NET SDK 9", PackageID: "dotnet-9.0-sdk", CategoryType: "sdk", Description: ".NET 9 SDK."},
								{Name: ".NET SDK 8", PackageID: "dotnet-8.0-sdk", CategoryType: "sdk", Description: ".NET 8 SDK."},
								{Name: ".NET SDK 7", PackageID: "dotnet-7.0-sdk", CategoryType: "sdk", Description: ".NET 7 SDK."},
								{Name: ".NET SDK 6", PackageID: "dotnet-6.0-sdk", CategoryType: "sdk", Description: ".NET 6 SDK."},
								{Name: ".NET SDK 5", PackageID: "dotnet-5.0-sdk", CategoryType: "sdk", Description: ".NET 5 SDK."},
							},
						},
						{
							Name:         "Java",
							CategoryType: "runtime",
							Description:  "Adoptium Java runtimes and development kits.",
							Apps: []Package{
								{Name: "JDK 25 (Adoptium)", PackageID: "temurin25", CategoryType: "runtime", Description: "Adoptium Java Development Kit 25."},
								{Name: "JDK 21 (Adoptium)", PackageID: "temurin21", CategoryType: "runtime", Description: "Adoptium Java Development Kit 21."},
								{Name: "JDK 17 (Adoptium)", PackageID: "temurin17", CategoryType: "runtime", Description: "Adoptium Java Development Kit 17."},
								{Name: "JDK 11 (Adoptium)", PackageID: "temurin11", CategoryType: "runtime", Description: "Adoptium Java Development Kit 11."},
								{Name: "JDK 8 (Adoptium)", PackageID: "temurin8", CategoryType: "runtime", Description: "Adoptium Java Development Kit 8."},
								{Name: "JRE 25 (Adoptium)", PackageID: "temurin25jre", CategoryType: "runtime", Description: "Adoptium Java Runtime Environment 25."},
								{Name: "JRE 21 (Adoptium)", PackageID: "temurin21jre", CategoryType: "runtime", Description: "Adoptium Java Runtime Environment 21."},
								{Name: "JRE 17 (Adoptium)", PackageID: "temurin17jre", CategoryType: "runtime", Description: "Adoptium Java Runtime Environment 17."},
								{Name: "JRE 11 (Adoptium)", PackageID: "temurin11jre", CategoryType: "runtime", Description: "Adoptium Java Runtime Environment 11."},
								{Name: "JRE 8 (Adoptium)", PackageID: "temurin8jre", CategoryType: "runtime", Description: "Adoptium Java Runtime Environment 8."},
							},
						},
						{
							Name:         "Node.js",
							CategoryType: "runtime",
							Description:  "Node.js runtime and package tooling.",
							Apps: []Package{
								{Name: "Node.js LTS", PackageID: "nodejs-lts", CategoryType: "runtime", Description: "Node.js LTS runtime and npm."},
							},
						},
						{
							Name:         "Python",
							CategoryType: "runtime",
							Description:  "Python runtime and package tools.",
							Apps: []Package{
								{Name: "Python 3", PackageID: "python", CategoryType: "runtime", Description: "Python runtime and package tools."},
							},
						},
						{
							Name:         "Toolchains",
							CategoryType: "runtime",
							Description:  "Compiler toolchains and build systems.",
							Apps: []Package{
								{Name: "Go", PackageID: "golang", CategoryType: "runtime", Description: "Go programming language toolchain."},
								{Name: "Rustup", PackageID: "rustup.install", CategoryType: "runtime", Description: "Rust toolchain installer and version manager."},
								{Name: "LLVM", PackageID: "llvm", CategoryType: "runtime", Description: "LLVM compiler infrastructure."},
								{Name: "MinGW", PackageID: "mingw", CategoryType: "runtime", Description: "Minimalist GNU toolchain for Windows."},
								{Name: "CMake", PackageID: "cmake", CategoryType: "runtime", Description: "Cross-platform build system generator."},
							},
						},
						{
							Name:         "Visual C++ Redistributables",
							CategoryType: "runtime",
							Description:  "Microsoft Visual C++ runtime packages for legacy and current Windows applications.",
							Apps: []Package{
								{Name: "VC++ Redist 2010 x86/x64", PackageID: "vcredist2010", CategoryType: "runtime", Description: "Microsoft Visual C++ 2010 runtime components for x86 and x64 applications."},
								{Name: "VC++ Redist 2012 x86/x64", PackageID: "vcredist2012", CategoryType: "runtime", Description: "Microsoft Visual C++ 2012 runtime components for x86 and x64 applications."},
								{Name: "VC++ Redist 2013 x86/x64", PackageID: "vcredist2013", CategoryType: "runtime", Description: "Microsoft Visual C++ 2013 runtime components for x86 and x64 applications."},
								{Name: "VC++ Redist 2015-2022 x86/x64", PackageID: "vcredist140", CategoryType: "runtime", Description: "Current Microsoft Visual C++ runtime components for x86 and x64 applications, covering Visual Studio 2015 through 2022."},
							},
						},
					},
				},
				{
					Name:         "Terminals & CLI",
					CategoryType: "subcategory",
					Description:  "Terminal emulators, shells, and command-line utilities.",
					Apps: []Package{
						{Name: "Windows Terminal", PackageID: "microsoft-windows-terminal", CategoryType: "terminal", Description: "Modern Microsoft terminal app."},
						{Name: "PowerShell 7", PackageID: "powershell-core", CategoryType: "terminal", Description: "Modern cross-platform PowerShell."},
						{Name: "WezTerm", PackageID: "wezterm", CategoryType: "terminal", Description: "GPU-accelerated terminal emulator."},
						{Name: "Fastfetch", PackageID: "fastfetch", CategoryType: "terminal", Description: "Fast system information command-line tool."},
						{Name: "FZF", PackageID: "fzf", CategoryType: "terminal", Description: "Command-line fuzzy finder."},
						{Name: "ripgrep", PackageID: "ripgrep", CategoryType: "terminal", Description: "Fast recursive text search tool."},
						{Name: "Codex", PackageID: "codex", CategoryType: "terminal", Description: "OpenAI Codex CLI coding agent."},
					},
				},
				{
					Name:         "Containers",
					CategoryType: "subcategory",
					Description:  "Container runtimes and desktop container managers.",
					Apps: []Package{
						{Name: "Docker Desktop", PackageID: "docker-desktop", CategoryType: "container", Description: "Docker container runtime and desktop app."},
						{Name: "Podman Desktop", PackageID: "podman-desktop", CategoryType: "container", Description: "Desktop manager for Podman and containers."},
					},
				},
				{
					Name:         "API & Databases",
					CategoryType: "subcategory",
					Description:  "API clients, database clients, and local database servers.",
					Apps: []Package{
						{Name: "Postman", PackageID: "postman", CategoryType: "database", Description: "API development and testing client."},
						{Name: "Bruno", PackageID: "bruno", CategoryType: "database", Description: "Git-friendly API client."},
						{Name: "Insomnia", PackageID: "insomnia-rest-api-client", CategoryType: "database", Description: "REST, GraphQL, and API client."},
						{Name: "DBeaver", PackageID: "dbeaver", CategoryType: "database", Description: "Universal database client."},
						{Name: "PostgreSQL", PackageID: "postgresql", CategoryType: "database", Description: "PostgreSQL database server."},
						{Name: "MySQL", PackageID: "mysql", CategoryType: "database", Description: "MySQL database server."},
						{Name: "MongoDB Compass", PackageID: "mongodb-compass", CategoryType: "database", Description: "MongoDB desktop GUI client."},
					},
				},
			},
		},
		{
			Name:         "Media",
			CategoryType: "category",
			Description:  "Media playback, recording, image editing, graphics, screenshots, and disc tools.",
			Categories: []Category{
				{
					Name:         "Playback & Audio",
					CategoryType: "subcategory",
					Description:  "Media players, audio tools, codecs, and streaming apps.",
					Apps: []Package{
						{Name: "iTunes", PackageID: "itunes", CategoryType: "media", Description: "Apple media library, playback, and device sync app."},
						{Name: "VLC", PackageID: "vlc", CategoryType: "media", Description: "Media player for video and audio."},
						{Name: "AIMP", PackageID: "aimp", CategoryType: "media", Description: "Lightweight audio player with playlist and format support."},
						{Name: "foobar2000", PackageID: "foobar2000", CategoryType: "media", Description: "Advanced audio player with a compact, customizable interface."},
						{Name: "Winamp", PackageID: "winamp", CategoryType: "media", Description: "Classic music player for local audio collections."},
						{Name: "MusicBee", PackageID: "musicbee", CategoryType: "media", Description: "Music manager and player for large local libraries."},
						{Name: "Audacious", PackageID: "audacious", CategoryType: "media", Description: "Lightweight audio player focused on sound quality and codec support."},
						{Name: "Audacity", PackageID: "audacity", CategoryType: "media", Description: "Audio recording and editing tool."},
						{Name: "K-Lite Codecs", PackageID: "k-litecodecpackfull", CategoryType: "media", Description: "Codec pack for broad video and audio playback support."},
						{Name: "GOM", PackageID: "gom-player", CategoryType: "media", Description: "Video player with wide codec and subtitle support."},
						{Name: "mpv", PackageID: "mpvio", CategoryType: "media", Description: "Minimal, keyboard-driven media player for audio and video playback."},
						{Name: "Spotify", PackageID: "spotify", CategoryType: "media", Description: "Music streaming desktop app."},
						{Name: "OBS Studio", PackageID: "obs-studio", CategoryType: "media", Description: "Recording and streaming studio."},
						{Name: "Kdenlive", PackageID: "kdenlive", CategoryType: "media", Description: "Open source video editor."},
						{Name: "HandBrake", PackageID: "handbrake", CategoryType: "media", Description: "Video transcoder and converter."},
						{Name: "yt-dlp", PackageID: "yt-dlp", CategoryType: "media", Description: "Command-line video downloader."},
						{Name: "FFmpeg", PackageID: "ffmpeg", CategoryType: "media", Description: "Audio and video processing toolkit."},
					},
				},
				{
					Name:         "Images & Graphics",
					CategoryType: "subcategory",
					Description:  "Image editors, viewers, screenshots, illustration, and 3D tools.",
					Apps: []Package{
						{Name: "Krita", PackageID: "krita", CategoryType: "graphics", Description: "Digital painting and illustration app."},
						{Name: "Blender", PackageID: "blender", CategoryType: "graphics", Description: "3D creation suite for modeling, rendering, and animation."},
						{Name: "Paint.NET", PackageID: "paint.net", CategoryType: "graphics", Description: "Lightweight image editor for Windows."},
						{Name: "GIMP", PackageID: "gimp", CategoryType: "graphics", Description: "Open source image editor."},
						{Name: "IrfanView", PackageID: "irfanview", CategoryType: "graphics", Description: "Fast image viewer and basic editor."},
						{Name: "XnView", PackageID: "xnview", CategoryType: "graphics", Description: "Image viewer and organizer."},
						{Name: "Inkscape", PackageID: "inkscape", CategoryType: "graphics", Description: "Vector graphics editor."},
						{Name: "FastStone Image Viewer", PackageID: "fsviewer", CategoryType: "graphics", Description: "Image browser, converter, and editor."},
						{Name: "Greenshot", PackageID: "greenshot", CategoryType: "graphics", Description: "Screenshot tool with annotation support."},
						{Name: "Lightshot", PackageID: "lightshot", CategoryType: "graphics", Description: "Simple screenshot capture and sharing tool."},
						{Name: "ImageGlass", PackageID: "imageglass", CategoryType: "graphics", Description: "Modern image viewer."},
						{Name: "ShareX", PackageID: "sharex", CategoryType: "graphics", Description: "Screenshot, screen capture, and sharing tool."},
						{Name: "ScreenToGif", PackageID: "screentogif", CategoryType: "graphics", Description: "Screen, webcam, and sketchboard recorder."},
						{Name: "Flameshot", PackageID: "flameshot", CategoryType: "graphics", Description: "Screenshot tool with annotation features."},
					},
				},
				{
					Name:         "Disc Tools",
					CategoryType: "subcategory",
					Description:  "CD, DVD, and image burning utilities.",
					Apps: []Package{
						{Name: "ImgBurn", PackageID: "imgburn", CategoryType: "disc", Description: "Disc image and optical media burning tool."},
						{Name: "CDBurnerXP", PackageID: "cdburnerxp", CategoryType: "disc", Description: "CD, DVD, Blu-ray, and ISO burning utility."},
						{Name: "InfraRecorder", PackageID: "infrarecorder", CategoryType: "disc", Description: "Open source CD and DVD burning utility."},
					},
				},
			},
		},
		{
			Name:         "Gaming",
			CategoryType: "category",
			Description:  "Game launchers and gaming communication tools.",
			Apps: []Package{
				{Name: "Steam", PackageID: "steam", CategoryType: "gaming", Description: "Steam game launcher and store."},
				{Name: "Epic Games Launcher", PackageID: "epicgameslauncher", CategoryType: "gaming", Description: "Epic Games Store launcher."},
				{Name: "Heroic Games Launcher", PackageID: "heroic-games-launcher", CategoryType: "gaming", Description: "Open source launcher for Epic, GOG, and Amazon games."},
				{Name: "Prism Launcher", PackageID: "prismlauncher", CategoryType: "gaming", Description: "Minecraft launcher for multiple instances and modded setups."},
				{Name: "Discord", PackageID: "discord", CategoryType: "gaming", Description: "Voice and chat app for communities."},
				{Name: "Parsec", PackageID: "parsec", CategoryType: "gaming", Description: "Low-latency remote desktop and game streaming app."},
				{Name: "Moonlight", PackageID: "moonlight", CategoryType: "gaming", Description: "GameStream client for remote gaming."},
				{Name: "Sunshine", PackageID: "sunshine", CategoryType: "gaming", Description: "Self-hosted game streaming host."},
				{Name: "MSI Afterburner", PackageID: "msiafterburner", CategoryType: "gaming", Description: "GPU tuning and monitoring utility."},
			},
		},
		{
			Name:         "Utilities",
			CategoryType: "category",
			Description:  "Windows utilities for files, remote access, security, productivity, and system maintenance.",
			Categories: []Category{
				{
					Name:         "Remote Access",
					CategoryType: "subcategory",
					Description:  "Remote desktop and VNC tools.",
					Apps: []Package{
						{Name: "AnyDesk", PackageID: "anydesk", CategoryType: "remote", Description: "Remote desktop access tool."},
						{Name: "TeamViewer", PackageID: "teamviewer", CategoryType: "remote", Description: "Remote access and support tool."},
						{Name: "RealVNC Server", PackageID: "vnc-connect", CategoryType: "remote", Description: "RealVNC server for remote desktop access."},
						{Name: "RealVNC Viewer", PackageID: "vnc-viewer", CategoryType: "remote", Description: "RealVNC viewer for connecting to VNC hosts."},
						{Name: "TightVNC", PackageID: "tightvnc", CategoryType: "remote", Description: "VNC remote control software."},
						{Name: "RustDesk", PackageID: "rustdesk", CategoryType: "remote", Description: "Open source remote desktop tool."},
						{Name: "Barrier", PackageID: "barrier", CategoryType: "remote", Description: "Keyboard and mouse sharing across computers."},
						{Name: "scrcpy", PackageID: "scrcpy", CategoryType: "remote", Description: "Android screen mirroring and control tool."},
						{Name: "ADB Platform Tools", PackageID: "adb", CategoryType: "remote", Description: "Android Debug Bridge platform tools."},
					},
				},
				{
					Name:         "File & System",
					CategoryType: "subcategory",
					Description:  "File copy, cleanup, search, launchers, and system shell utilities.",
					Apps: []Package{
						{Name: "Everything", PackageID: "everything", CategoryType: "utility", Description: "Fast local file search tool."},
						{Name: "TeraCopy", PackageID: "teracopy", CategoryType: "utility", Description: "File copy utility with verification and queueing."},
						{Name: "Revo Uninstaller", PackageID: "revo-uninstaller", CategoryType: "utility", Description: "Application uninstaller and cleanup tool."},
						{Name: "Launchy", PackageID: "launchy", CategoryType: "utility", Description: "Keyboard-driven application launcher."},
						{Name: "WinDirStat", PackageID: "windirstat", CategoryType: "utility", Description: "Disk usage analyzer and cleanup helper."},
						{Name: "WizTree", PackageID: "wiztree", CategoryType: "utility", Description: "Fast disk space analyzer."},
						{Name: "Glary Utilities", PackageID: "glaryutilities-free", CategoryType: "utility", Description: "System cleanup and optimization utility."},
						{Name: "Open-Shell", PackageID: "open-shell", CategoryType: "utility", Description: "Classic Start menu and shell enhancements."},
						{Name: "CCleaner", PackageID: "ccleaner", CategoryType: "utility", Description: "System cleanup utility."},
						{Name: "PowerToys", PackageID: "powertoys", CategoryType: "utility", Description: "Microsoft utilities for Windows power users."},
						{Name: "Google Earth", PackageID: "googleearthpro", CategoryType: "utility", Description: "Desktop globe, maps, and geographic exploration app."},
						{Name: "AutoHotkey", PackageID: "autohotkey", CategoryType: "utility", Description: "Automation and hotkey scripting tool."},
						{Name: "Ventoy", PackageID: "ventoy", CategoryType: "utility", Description: "Multiboot USB drive creator."},
						{Name: "Bulk Crap Uninstaller", PackageID: "bulk-crap-uninstaller", CategoryType: "utility", Description: "Bulk application uninstaller and cleanup tool."},
						{Name: "HWiNFO64", PackageID: "hwinfo", CategoryType: "utility", Description: "Hardware information and monitoring tool."},
						{Name: "HWMonitor", PackageID: "hwmonitor", CategoryType: "utility", Description: "Hardware sensor monitoring tool."},
						{Name: "CPU-Z", PackageID: "cpu-z", CategoryType: "utility", Description: "CPU, motherboard, memory, and system information tool."},
						{Name: "GPU-Z", PackageID: "gpu-z", CategoryType: "utility", Description: "Graphics card information utility."},
						{Name: "System Informer", PackageID: "systeminformer", CategoryType: "utility", Description: "Modern process, service, and system monitor."},
						{Name: "Process Explorer", PackageID: "procexp", CategoryType: "utility", Description: "Sysinternals process inspection tool."},
						{Name: "Autoruns", PackageID: "autoruns", CategoryType: "utility", Description: "Sysinternals startup entry inspection tool."},
						{Name: "TreeSize Free", PackageID: "treesizefree", CategoryType: "utility", Description: "Disk usage analyzer."},
						{Name: "EarTrumpet", PackageID: "eartrumpet", CategoryType: "utility", Description: "Per-app volume control for Windows."},
						{Name: "StartAllBack", PackageID: "startallback", CategoryType: "utility", Description: "Windows taskbar, Start menu, and Explorer customization."},
						{Name: "TranslucentTB", PackageID: "translucenttb", CategoryType: "utility", Description: "Windows taskbar transparency utility."},
						{Name: "F.lux", PackageID: "flux", CategoryType: "utility", Description: "Display color temperature adjustment tool."},
						{Name: "Twinkle Tray", PackageID: "twinkle-tray", CategoryType: "utility", Description: "External monitor brightness control."},
						{Name: "UniGetUI", PackageID: "unigetui", CategoryType: "utility", Description: "GUI for package managers including Chocolatey and winget."},
					},
				},
				{
					Name:         "Archives",
					CategoryType: "subcategory",
					Description:  "Archive managers and compression tools.",
					Apps: []Package{
						{Name: "7-Zip", PackageID: "7zip", CategoryType: "archive", Description: "File archiver with broad format support."},
						{Name: "WinRAR", PackageID: "winrar", CategoryType: "archive", Description: "Archive manager for RAR, ZIP, and other formats."},
						{Name: "PeaZip", PackageID: "peazip", CategoryType: "archive", Description: "Open source archive manager."},
					},
				},
				{
					Name:         "Security & Passwords",
					CategoryType: "subcategory",
					Description:  "Password managers and malware removal tools.",
					Apps: []Package{
						{Name: "Bitwarden", PackageID: "bitwarden", CategoryType: "security", Description: "Password manager desktop app."},
						{Name: "KeePass 2", PackageID: "keepass", CategoryType: "security", Description: "Local password manager."},
						{Name: "Malwarebytes", PackageID: "malwarebytes", CategoryType: "security", Description: "Anti-malware scanning and cleanup tool."},
						{Name: "VeraCrypt", PackageID: "veracrypt", CategoryType: "security", Description: "Disk and volume encryption tool."},
						{Name: "BleachBit", PackageID: "bleachbit", CategoryType: "security", Description: "Privacy-focused cleanup utility."},
						{Name: "SimpleWall", PackageID: "simplewall", CategoryType: "security", Description: "Windows Filtering Platform firewall control tool."},
					},
				},
				{
					Name:         "Network & Transfer",
					CategoryType: "subcategory",
					Description:  "FTP, SSH, torrent, and file transfer clients.",
					Apps: []Package{
						{Name: "FileZilla", PackageID: "filezilla", CategoryType: "network", Description: "FTP, FTPS, and SFTP client."},
						{Name: "WinSCP", PackageID: "winscp", CategoryType: "network", Description: "SFTP, SCP, FTP, and WebDAV file transfer client."},
						{Name: "PuTTY", PackageID: "putty", CategoryType: "network", Description: "SSH and Telnet client."},
						{Name: "qBittorrent", PackageID: "qbittorrent", CategoryType: "network", Description: "BitTorrent client."},
						{Name: "Tailscale", PackageID: "tailscale", CategoryType: "network", Description: "Mesh VPN client."},
						{Name: "WireGuard", PackageID: "wireguard", CategoryType: "network", Description: "WireGuard VPN client."},
						{Name: "ZeroTier", PackageID: "zerotier-one", CategoryType: "network", Description: "Virtual networking and mesh VPN client."},
						{Name: "Wireshark", PackageID: "wireshark", CategoryType: "network", Description: "Network protocol analyzer."},
						{Name: "Nmap", PackageID: "nmap", CategoryType: "network", Description: "Network discovery and security scanner."},
						{Name: "Syncthing", PackageID: "syncthing", CategoryType: "network", Description: "Continuous file synchronization tool."},
						{Name: "LocalSend", PackageID: "localsend", CategoryType: "network", Description: "Local network file sharing app."},
					},
				},
				{
					Name:         "Cloud & Documents",
					CategoryType: "subcategory",
					Description:  "Cloud sync, office suites, notes, and document readers.",
					Apps: []Package{
						{Name: "Dropbox", PackageID: "dropbox", CategoryType: "productivity", Description: "Cloud file sync desktop app."},
						{Name: "Google Drive", PackageID: "googledrive", CategoryType: "productivity", Description: "Google Drive desktop sync app."},
						{Name: "LibreOffice", PackageID: "libreoffice-fresh", CategoryType: "productivity", Description: "Open source office suite."},
						{Name: "OpenOffice", PackageID: "openoffice", CategoryType: "productivity", Description: "Apache OpenOffice productivity suite."},
						{Name: "Foxit Reader", PackageID: "foxitreader", CategoryType: "productivity", Description: "PDF reader."},
						{Name: "Evernote", PackageID: "evernote", CategoryType: "productivity", Description: "Notes and organization app."},
						{Name: "OnlyOffice", PackageID: "onlyoffice", CategoryType: "productivity", Description: "Office suite for documents, spreadsheets, and presentations."},
						{Name: "SumatraPDF", PackageID: "sumatrapdf", CategoryType: "productivity", Description: "Lightweight PDF and ebook reader."},
						{Name: "Claude", PackageID: "claude", CategoryType: "productivity", Description: "Anthropic Claude desktop app."},
					},
				},
				{
					Name:         "Editors",
					CategoryType: "subcategory",
					Description:  "Text editors and code-oriented desktop apps.",
					Apps: []Package{
						{Name: "Notepad++", PackageID: "notepadplusplus", CategoryType: "editor", Description: "Fast text and source code editor."},
						{Name: "Cursor", PackageID: "cursoride", CategoryType: "editor", Description: "AI-powered code editor based on VS Code."},
						{Name: "WinMerge", PackageID: "winmerge", CategoryType: "editor", Description: "File and folder comparison tool."},
					},
				},
				{
					Name:         "Imaging & Virtualization",
					CategoryType: "subcategory",
					Description:  "USB imaging, virtual machines, and installer utilities.",
					Apps: []Package{
						{Name: "balenaEtcher", PackageID: "etcher", CategoryType: "virtualization", Description: "Bootable USB and SD card image writer."},
						{Name: "VirtualBox", PackageID: "virtualbox", CategoryType: "virtualization", Description: "Virtual machine platform."},
					},
				},
			},
		},
	}
}
