package catalog

import (
	"bytes"
	"encoding/json"
	"fmt"
)

const GeneratedCatalogPrefix = "// Code generated by go run ./cmd/export-catalog; DO NOT EDIT.\nwindow.FRESHCTL_CATALOG = "
const GeneratedCatalogSuffix = ";\n"

type ExportPackage struct {
	Name        string `json:"name"`
	PackageID   string `json:"packageId"`
	Category    string `json:"category"`
	Type        string `json:"type"`
	Source      string `json:"source"`
	Verified    bool   `json:"verified"`
	Description string `json:"description"`
}

func Export(categories []Category) []ExportPackage {
	packages := make([]ExportPackage, 0)
	collectExportPackages(categories, &packages)
	return packages
}

func GeneratedCatalogJS(categories []Category) ([]byte, error) {
	packages := Export(categories)
	payload, err := json.MarshalIndent(packages, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode catalog: %w", err)
	}

	var out bytes.Buffer
	out.WriteString(GeneratedCatalogPrefix)
	out.Write(payload)
	out.WriteString(GeneratedCatalogSuffix)
	return out.Bytes(), nil
}

func DecodeGeneratedCatalogJS(content []byte) ([]ExportPackage, error) {
	if !bytes.HasPrefix(content, []byte(GeneratedCatalogPrefix)) || !bytes.HasSuffix(content, []byte(GeneratedCatalogSuffix)) {
		return nil, fmt.Errorf("generated catalog has unexpected wrapper")
	}

	jsonPayload := bytes.TrimSuffix(bytes.TrimPrefix(content, []byte(GeneratedCatalogPrefix)), []byte(GeneratedCatalogSuffix))
	var packages []ExportPackage
	if err := json.Unmarshal(jsonPayload, &packages); err != nil {
		return nil, fmt.Errorf("decode generated catalog: %w", err)
	}
	return packages, nil
}

func collectExportPackages(categories []Category, packages *[]ExportPackage) {
	for _, category := range categories {
		collectExportPackages(category.Categories, packages)
		for _, app := range category.Apps {
			*packages = append(*packages, ExportPackage{
				Name:        app.Name,
				PackageID:   app.PackageID,
				Category:    app.Category,
				Type:        string(app.Type),
				Source:      string(app.Source),
				Verified:    app.Verified,
				Description: app.Description,
			})
		}
	}
}
